### ISSUE TITLE
Appsflyer 5.2.0 React-Native Integration failing for Android

### ISSUE THREAD

**Issue by Chuloo** [AppsFlyerSDK/appsflyer-react-native-plugin#151]
# Report

## Plugin Version

5.2.0

## On what Platform are you having the issue?

Android

## What did you do?

I installed and set up the SDK on React-Native, but I don't see the android device's data on the Appsflyer dashboard, only ios.

## What did you expect to happen?

I expected to see data from ios and android, installs data for instance.

## What happened instead?

No Android Installs data shown on my account dashboard. Also, I can see on firebase that all requests to the appsflyer android API throws a 404.

## Please provide any other relevant information.

Here's a screenshot of what I got from my firebase app performance data.

![image](https://user-images.githubusercontent.com/22301208/83352983-74ccfb00-a360-11ea-8628-d769a2e85233.png)

![image](https://user-images.githubusercontent.com/22301208/83353061-edcc5280-a360-11ea-824f-f6a237785cb2.png)

**Comment by pqminh** [comment]
same here
react-native-appsflyer@5.2.0
react-native@0.61.5

`
2020-06-04 14:48:05.442 11846-11942/com.wbmobile.app.stg D/AppsFlyer: Starting Tracking
2020-06-04 14:48:05.464 11846-11942/com.wbmobile.app.stg D/AppsFlyer_5.2.0: Initializing AppsFlyer SDK: (v5.2.0.311)
2020-06-04 14:48:05.477 11846-11942/com.wbmobile.app.stg I/AppsFlyer_5.2.0: Sending first launch for this session!
2020-06-04 14:48:05.494 11846-11942/com.wbmobile.app.stg I/AppsFlyer_5.2.0: Starting AppsFlyer Tracking: (v5.2.0.311)
2020-06-04 14:48:05.501 11846-11942/com.wbmobile.app.stg I/AppsFlyer_5.2.0: Build Number: 311
2020-06-04 14:48:05.509 11846-11942/com.wbmobile.app.stg D/AppsFlyer_5.2.0: Loading properties..
2020-06-04 14:48:05.517 11846-11942/com.wbmobile.app.stg D/AppsFlyer_5.2.0: Done loading properties: true
2020-06-04 14:48:05.639 11846-12017/com.wbmobile.app.stg I/AppsFlyer_5.2.0: sendTrackingWithEvent from activity: com.wbmobile.MainApplication
2020-06-04 14:48:05.645 11846-11941/com.wbmobile.app.stg I/ReactNativeJS: 'initAppsFlyer.result', 'Success'
2020-06-04 14:48:05.650 11846-12017/com.wbmobile.app.stg I/AppsFlyer_5.2.0: Trying to fetch GAID..
2020-06-04 14:48:05.786 11846-12017/com.wbmobile.app.stg I/AppsFlyer_5.2.0: ******* sendTrackingWithEvent: Launch
2020-06-04 14:48:05.820 11846-12017/com.wbmobile.app.stg I/AppsFlyer_5.2.0: IMEI was not collected.
2020-06-04 14:48:05.828 11846-12017/com.wbmobile.app.stg I/AppsFlyer_5.2.0: Android ID was not collected.
2020-06-04 14:48:05.860 11846-12017/com.wbmobile.app.stg I/AppsFlyer_5.2.0: AppsFlyer: first launch date: 2020-06-04_073923+0000
2020-06-04 14:48:05.867 11846-12017/com.wbmobile.app.stg W/AppsFlyer_5.2.0: Cannot verify existence of our InstanceID Listener Service in the manifest. Please refer to documentation.
2020-06-04 14:48:05.873 11846-12017/com.wbmobile.app.stg D/AppsFlyer_5.2.0: didConfigureTokenRefreshService=false
2020-06-04 14:48:05.879 11846-12017/com.wbmobile.app.stg D/AppsFlyer_5.2.0: No deep link detected
2020-06-04 14:48:05.912 11846-12017/com.wbmobile.app.stg I/AppsFlyer_5.2.0: AppsFlyerLib.sendTrackingWithEvent
2020-06-04 14:48:06.572 11846-12017/com.wbmobile.app.stg I/AppsFlyer_5.2.0: url: https://launches.appsflyer.com/api/v5.2/androidevent?app_id=com.wbmobile.app.stg&buildnumber=5.2.0
2020-06-04 14:48:06.592 11846-12017/com.wbmobile.app.stg I/AppsFlyer_5.2.0: data: {"country":"VN","af_timestamp":"1591256885694","appsflyerKey":"Y********************9","af_events_api":"1","isFirstCall":"true","registeredUninstall":false,"cell":{"mnc":0,"mcc":0},"operator":"","network":"WIFI","timepassedsincelastlaunch":"19","open_referrer":"","af_v2":"e771d27b2e7e10e0da7d2392e13368a11ab201cb","sig":"FAC61745DC0903786FB9EDE62A962B399F7348F0BB6F899B8332667591033B9C","uid":"1591256361771-440564215202838873","kef756f":"58d40f029ebe60814819121b0c531a0d591f0c5b1e1f","isGaidWithGps":"true","lang_code":"vi","installDate":"2020-06-04_073740+0000","app_version_code":"87","firstLaunchDate":"2020-06-04_073923+0000","ivc":false,"model":"SM-G610F","lang":"Tiếng Việt","brand":"samsung","deviceType":"user","last_boot_time":1590573398075,"product":"on7xeltedd","deviceData":{"cpu_abi":"armeabi-v7a","build_display_id":"M1AJQ.G610FDXU1CRL2","btch":"no","dim":{"size":"2","ydp":"403.041","xdp":"403.411","y_px":"1920","x_px":"1080","d_dpi":"480"},"arch":"","btl":"100.0","cpu_abi2":"armeabi"},"date2":"2020-06-04_143740+0700","counter":"5","date1":"2020-06-04_143740+0700","advertiserId":"550f597d-d517-45d5-9503-a5734d427bdf","advertiserIdEnabled":"true","af_v":"9d65c7e55f147dd13e0723f8dacd407f4ee59f74","carrier":"","disk":"18417\/25964","af_preinstalled":"false","iaecounter":"0","sc_o":"p","tokenRefreshConfigured":false,"sdk":"27","app_version_name":"1.0.87-stg","device":"on7xelte","platformextension":"android_reactNative","cksm_v1":"c1200b345879c4302f26c56206ae4f6bcd"}
2020-06-04 14:48:07.910 11846-12017/com.wbmobile.app.stg I/AppsFlyer_5.2.0: response code: 404
2020-06-04 14:48:07.935 11846-12030/com.wbmobile.app.stg I/AppsFlyer_5.2.0: Calling server for attribution url: https://gcdsdk.appsflyer.com/install_data/v4.0/com.wbmobile.app.stg?devkey=Y********************9&device_id=1591256361771-440564215202838873
2020-06-04 14:48:10.261 11846-12030/com.wbmobile.app.stg D/AppsFlyer_5.2.0: Calling onConversionFailure with:
    Error connection to server: 400
2020-06-04 14:48:10.272 11846-12030/com.wbmobile.app.stg I/AppsFlyer_5.2.0: AttributionIdFetcher response code: 400  url: https://gcdsdk.appsflyer.com/install_data/v4.0/com.wbmobile.app.stg?devkey=Y********************9&device_id=1591256361771-440564215202838873
2020-06-04 14:56:40.501 12101-12518/com.wbmobile.app.stg I/AppsFlyer_5.2.0: sendTrackingWithEvent from activity: com.wbmobile.MainApplication
2020-06-04 14:56:40.506 12101-12518/com.wbmobile.app.stg I/AppsFlyer_5.2.0: Trying to fetch GAID..
2020-06-04 14:56:40.662 12101-12518/com.wbmobile.app.stg I/AppsFlyer_5.2.0: ******* sendTrackingWithEvent: login
2020-06-04 14:56:40.714 12101-12518/com.wbmobile.app.stg I/AppsFlyer_5.2.0: IMEI was not collected.
2020-06-04 14:56:40.724 12101-12518/com.wbmobile.app.stg I/AppsFlyer_5.2.0: Android ID was not collected.
2020-06-04 14:56:40.766 12101-12518/com.wbmobile.app.stg I/AppsFlyer_5.2.0: AppsFlyer: first launch date: 2020-06-04_073923+0000
2020-06-04 14:56:40.772 12101-12518/com.wbmobile.app.stg W/AppsFlyer_5.2.0: Cannot verify existence of our InstanceID Listener Service in the manifest. Please refer to documentation.
2020-06-04 14:56:40.777 12101-12518/com.wbmobile.app.stg D/AppsFlyer_5.2.0: didConfigureTokenRefreshService=false
2020-06-04 14:56:40.822 12101-12518/com.wbmobile.app.stg I/AppsFlyer_5.2.0: AppsFlyerLib.sendTrackingWithEvent
2020-06-04 14:56:41.190 12101-12518/com.wbmobile.app.stg I/AppsFlyer_5.2.0: url: https://inapps.appsflyer.com/api/v5.2/androidevent?app_id=com.wbmobile.app.stg&buildnumber=5.2.0
2020-06-04 14:56:41.198 12101-12518/com.wbmobile.app.stg I/AppsFlyer_5.2.0: data: {"country":"VN","af_timestamp":"1591257400568","appsflyerKey":"Y********************9","af_events_api":"1","isFirstCall":"true","registeredUninstall":false,"cell":{"mnc":0,"mcc":0},"operator":"","network":"WIFI","af_v2":"37eb909de180f0357c6a9d93dd7a8995d8967443","sig":"FAC61745DC0903786FB9EDE62A962B399F7348F0BB6F899B8332667591033B9C","uid":"1591256361771-440564215202838873","eventValue":"{\"birthday\":\"1980-07-18\",\"gender\":\"Female\",\"user_name\":\"minhtest\",\"last_name\":\"Test\",\"phone_number\":\"+93123456789\",\"first_name\":\"Minh\",\"email\":\"m@rebus-tech.com\"}","isGaidWithGps":"true","lang_code":"vi","installDate":"2020-06-04_073740+0000","app_version_code":"87","firstLaunchDate":"2020-06-04_073923+0000","ivc":false,"eventName":"login","model":"SM-G610F","lang":"Tiếng Việt","brand":"samsung","deviceType":"user","last_boot_time":1590573398075,"product":"on7xeltedd","kef7960":"6668ef2a09e5a8bd4819121f0c531a0d591f0c5b1e1f","deviceData":{"cpu_abi":"armeabi-v7a","build_display_id":"M1AJQ.G610FDXU1CRL2","dim":{"size":"2","ydp":"403.041","xdp":"403.411","y_px":"1920","x_px":"1080","d_dpi":"480"},"arch":"","cpu_abi2":"armeabi"},"date2":"2020-06-04_143740+0700","counter":"8","date1":"2020-06-04_143740+0700","advertiserId":"550f597d-d517-45d5-9503-a5734d427bdf","advertiserIdEnabled":"true","af_v":"59cc6b4249c3ab1bde51656ff555b6960522f295","carrier":"","disk":"18417\/25964","af_preinstalled":"false","iaecounter":"1","sc_o":"p","tokenRefreshConfigured":false,"sdk":"27","app_version_name":"1.0.87-stg","device":"on7xelte","platformextension":"android_reactNative","cksm_v1":"2d0cf5d351467df3bff744546440bfd28b"}
2020-06-04 14:56:42.026 12101-12518/com.wbmobile.app.stg I/AppsFlyer_5.2.0: response code: 404
`

**Comment by Chuloo** [comment]
Mine is fixed, I needed to create an android app on Appsflyer, I had created only iOS previously :)

**Comment by pqminh** [comment]
I had created android staging with option:
3. Android out of store APK (Standalone, Amazon etc)
![image](https://user-images.githubusercontent.com/13993984/83733253-815e9580-a677-11ea-9fd2-8695cf6562c1.png)
but still get response 404

**Comment by pqminh** [comment]
fixed
we only add <meta-data android:name="CHANNEL" android:value="something"/> to AndroidManifest

**Comment by zhouchenyu000** [comment]
Same problem

version：
react-native-appsflyer@6.10.2

Solution：
On https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/API.md

![image](https://user-images.githubusercontent.com/77151742/236782490-3c9569f9-cf6d-4459-9f6d-f201f96c57d1.png)

It's strange that it's not placed in the Getting Started section.
