### ISSUE TITLE
Your app includes non-compliant SDK version

### ISSUE THREAD

**Issue by ovalwmaniero** [AppsFlyerSDK/appsflyer-react-native-plugin#392]
# Report
Hi, 
We are getting this error from Google Play Console as soon as we upload the APK

`
Your app includes non-compliant SDK version
Your app includes SDK com.segment.analytics.android:analytics or an SDK that one of your
libraries depends on, which collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers.
Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the
user data policy.
Starting from 12 August 2022 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the User Data policy
may be blocked from release. You may consider moving to another SDK; removing this SDK; or if available from your SDK provider, upgrading
to a policy-compliant version of this SDK that does not include the violating code.
According to the information provided by your SDK provider, you may consider upgrading to 4.10.1. Please consult the SDK provider for
further information.
ACTION REQUIRED: Upload a new compliant version AND deactivate the noncompliant version.
`

Since we are not using the above mentioned package anywhere, I found out after some digging that appsflyer uses com.segment.analytics.android.

Can you please confirm that? and if yes, can you please try to fix the error?

Thanks in advance

## Plugin Version

react-native-appsflyer 6.1.30

## On what Platform are you having the issue?

android

## What did you do?

Just build the apk and upload it to the Google Play Console

## What did you expect to happen?

Upload success without error

## What happened instead?

A warning is raised and shortly will become a blocker

**Comment by amit-kremer93** [comment]
Hii @ovalwmaniero can you please point to the place where the sdk uses this dependency?

**Comment by ovalwmaniero** [comment]
Hi @amit-kremer93,

Im not sure where is being used but from my digging process I found out that the only lib that uses com.segment.analytics.android is AppsFlyer.

I disassembled my compiled .dex 

![ss](https://user-images.githubusercontent.com/107558457/174016913-ffa6590e-38ed-46e3-ad61-f6d45d71632a.png)

and the only line that uses that SDK in my whole project compiled .dex is the one you see in the screenshot above.

**Comment by amit-kremer93** [comment]
@ovalwmaniero in our RN plugin we don't use segment. did you install [this](https://github.com/AppsFlyerSDK/appsflyer-segment-android-plugin) plugin also?

**Comment by ovalwmaniero** [comment]
@amit-kremer93 we don't use the segment plugin, maybe the segment dependency is getting included in the final SDK as a transitive dependency?

I guess that the Google Play console is only searching for a reference to the segment dependency and as soon as is found, the error is triggered, even if the library is not getting used.

**Comment by amit-kremer93** [comment]
It looks like it is related to our native android sdk so we will keep you updated.
Thank you.

**Comment by pedpess** [comment]
Hi @amit-kremer93 just to update you that Google nicely increased their deadline to fix this from the 28th of August to -> 24th of September. 😄

Would you have at this stage a forecast of when this update would land so we can update it?

**Comment by leolusoli** [comment]
Hi @amit-kremer93 hope you well. We're near to the block data for Google Play Store. Can you give us am estimated date when this will be fixed (if will be fixed)? Otherwise, we'll be obligated to remove the SDK from our app in order to continue to release out our application.

cc @ovalwmaniero

**Comment by pedpess** [comment]
@leolusoli Appsflyer team recently released a new version of the RN containing the updated Android SDK :). Just update. Cheers!

**Comment by leolusoli** [comment]
@pedpess Very nice news :) Thank you so much... Do you know if there's a changelog for review the other changes in addition to this one?

**Comment by pedpess** [comment]
@leolusoli there's but they don't write anything. I found out the SDK got updated because I saw the new version of the RN lib and I saw the diff comparing with the previous version

**Comment by guysarfatty-af** [comment]
@leolusoli @pedpess Thanks for your feedback!
We are working on a fix that will mitigate this issue, by removing the line that was referenced in the Google Play warning. 
I would like to emphasise that the line was used by the SDK to determine the type of plugin that is running the SDK, and by no means was it loading any additional library to be used inside the RN plugin.
Now this line has been removed from the code and the problem should be resolved.
We will issue a new version of the React Native plugin later this week as version 6.9.1. Thanks!

**Comment by leolusoli** [comment]
So @guysarfatty-af, @pedpess is not right to say that in the last current version (at the moment of writing: **6.8.2**) the issue is not resolved. Right?

**Comment by leolusoli** [comment]
Ok, no worries :) Thank you @pedpess

**Comment by leolusoli** [comment]
@guysarfatty-af News about that? The deadline is near.

**Comment by pedpess** [comment]
@leolusoli the version promised with the fix 6.9.1 was released 5 days ago, just update it and submit it to Google Play. 🤞🏻

**Comment by zirgulis** [comment]
Does anyone still getting warnings in regards to this? We have updated the `react-native-appsflyer` to `6.9.2` but google store support team says our latest app bundle is still not compliant. Would appreciate any inputs on this 🙏

**Comment by pedpess** [comment]
@zirgulis I would keep in 6.9.1 for now, but your version should have the update in theory. I stopped getting the complains after updating. Maybe you could try to update to the latest 6.9.4? Check their Android repo where you can see what was changed in the SDK, might help!

**Comment by sregg** [comment]
We also received this email from Google today saying our app update was rejected because the AppsFlyer SDK was collecting some data:

<img width="664" alt="image" src="https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/assets/1479283/42748ace-8fa1-4686-bf00-a2803a3ca212">

```
Issue details

We found an issue in the following area(s):

Version code 479: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: com.appsflyer:af-android-sdk
Version code 645: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: com.appsflyer:af-android-sdk, com.google.android.gms:play-services-measurement-impl
To bring your app into compliance, follow these steps:

com.appsflyer:af-android-sdk com.appsflyer:af-android-sdk: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.
com.google.android.gms:play-services-measurement-impl com.google.android.gms:play-services-measurement-impl: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.
```

Did anyone receive this? How did you fix it?

**Comment by phanhungphong0406** [comment]
> We also received this email from Google today saying our app update was rejected because the AppsFlyer SDK was collecting some data:
> 
> <img alt="image" width="664" src="https://private-user-images.githubusercontent.com/1479283/288819106-42748ace-8fa1-4686-bf00-a2803a3ca212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjE3NTAsIm5iZiI6MTcwMjAyMTQ1MCwicGF0aCI6Ii8xNDc5MjgzLzI4ODgxOTEwNi00Mjc0OGFjZS04ZmExLTQ2ODYtYmYwMC1hMjgwM2EzY2EyMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMDc0NDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjk4ODAxMGZiODJhNGQ4YzE3ZWFlZjUxYzdhMjNkOWY4NGJjNDk3YTRkMzI4ZjNiZjFlOTMxMGZkOWRjYmIxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3u292TivnlEqM7S8umccX3M9p9YnrxrgIMSMBkZ9UlE">
> ```
> Issue details
> 
> We found an issue in the following area(s):
> 
> Version code 479: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: com.appsflyer:af-android-sdk
> Version code 645: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: com.appsflyer:af-android-sdk, com.google.android.gms:play-services-measurement-impl
> To bring your app into compliance, follow these steps:
> 
> com.appsflyer:af-android-sdk com.appsflyer:af-android-sdk: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.
> com.google.android.gms:play-services-measurement-impl com.google.android.gms:play-services-measurement-impl: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.
> ```
> 
> Did anyone receive this? How did you fix it?

Me too, can you solve it? Please help me

**Comment by aouuthanapat** [comment]
> For now I changed our Data Safety form and checked the Device ID checkbox.

Is that working?

**Comment by sregg** [comment]
> > For now I changed our Data Safety form and checked the Device ID checkbox.
> 
> Is that working?
> 

Yeah Google approved the app after that. But ideally the AppsFlyer SDK doesn't collect the device ID.
